<main id="index">
    <div class="container">
        <div class = flex>
            <!-- Slider main container -->
            <div class="swiper-container">
                <!-- Additional required wrapper -->
                <div class="swiper-wrapper">
                    <!-- Slides -->
                    <?php foreach($projects as $project) :  ?>
                        <div class="swiper-slide">
                            <img src="<?= $wwwUrl ?>/images/illustrations/<?= $project['name']?>" alt="Photo du slider">
                        </div>
                    <?php endforeach ?>
                    <!-- If we need navigation buttons -->
                    <div class="swiper-button-prev swiper-button-white"></div>
                    <div class="swiper-button-next swiper-button-white"></div>
            
                    <!-- If we need scrollbar -->
                    <div class="swiper-scrollbar"></div>
                </div>
                <!-- If we need pagination -->
                <!-- <div class="swiper-pagination"></div> -->
            </div>
            <div class="flux">
                <h1><?= $actu[0]['titreActu']?></h1>
                <p><?= $actu[0]['texteActu']?></p>
                <p  class="lien"><a href="<?= $actu[0]['lienActu']?>"><?= $actu[0]['lienActu']?></a></p>
                <figure>
                    <a href="<?= $actu[0]['lienImage']?>">
                        <img src="<?= $wwwUrl ?>/images/illustrations/<?= $actu[0]['name']?>" alt="Photo actu"/>
                    </a>
                    <figcaption><?= $actu[0]['titreImage']?></figcaption> 
                </figure>
            </div>
        </div>
    </div>
</main>
