<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clairette</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/flexslider.css">
    <!-- Feuilles de styles du swiper -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/css/swiper.min.css">
    <!-- Feuilles de styles du flexslider -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
    <!-- <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla"> -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Montserrat+Subrayada&display=swap" rel="stylesheet"> 
    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
    <script src="<?= $wwwUrl ?>/js/jquery.flexslider-min.js" defer="true"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script >
    $(window).on('load', function() {
        $('.flexslider').flexslider({
            //  directionNav: false,
            controlNav: false, 
            // smoothHeight:true,
            // pauseOnHover: true
        });
    });
    </script>
    <!-- JavaScript du swiper -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/js/swiper.jquery.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function () {
        //initialize swiper when document ready  
        var mySwiper = new Swiper ('.swiper-container', {
            // Optional parameters
            autoplay: 5000,
            loop: true,
            scrollbar: '.swiper-scrollbar',
            scrollbarHide: true,
            slidesPerView: 'auto',
            centeredSlides: true,
            nextButton: '.swiper-button-next',
            prevButton: '.swiper-button-prev',
            effect: 'fade',
            speed: 1500
        })
    });
    </script>
</head>
<body>
    <header>
        <div class="container">
            <div class="flex">
                <!-- Interface admin -->
                <?php if (isset($_SESSION['user']) && $_SESSION['user']['role'] === 'admin') : ?>
                    <a href="<?= $requestUrl ?>/admin/home"><img src="<?= $wwwUrl ?>/images/logo4.png" alt="logo"></a>
                    <nav>
                        <a href="<?= $requestUrl ?>/admin/illustration">Illustration</a>
                        <a href="<?= $requestUrl ?>/admin/graphisme">Graphisme</a>
                        <a href="<?= $requestUrl ?>/admin/presentation">Présentation</a>
                    </nav>
                <!-- Interface utilisateur -->
                <?php else : ?>
                <a href="<?= $requestUrl ?>"><img src="<?= $wwwUrl ?>/images/logo4.png" alt="logo"></a>
                <nav>
                    <a href="<?= $requestUrl ?>/illustration">Illustration</a>
                    <a href="<?= $requestUrl ?>/graphisme">Graphisme</a>
                    <a href="<?= $requestUrl ?>/presentation">Présentation</a>
                </nav>
                <?php endif ?>
            </div>
        </div>
    </header>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
    <footer>
        <div class="container">
            <div class ="flex">
                <p> &amp;copy 2019 Clairette</p>
                <?php if (!isset($_SESSION['user'])) : ?>
                <a class="connect" href="<?= $requestUrl ?>/utilisateur"> connexion</a>
                <?php else : ?>
                <a class="connect" href="<?= $requestUrl ?>/logout"> déconnexion</a>
                <?php endif ?>
            </div>
        </div>
    </footer>
<!-- Code principal JavaScript de l'application -->
<script type=module src="<?= $wwwUrl ?>/js/main.js"></script>
</body>
</html>