<main id="about" >
<div class="container">
    <div class="flex">
        <?php
        // var_dump($presentations);
        // die;
        ?>
        <section class="presentation">
            <h1><?= $presentations[0]['titrePresentation']?></h1>
            <p><?= $presentations[0]['textePresentation']?></p>
        </section>
        <aside class="contact">
                <figure>
                    <img class="imgPresentation" src="<?= $wwwUrl ?>/images/illustrations/<?= $presentations[0]['name']?>"/>
                    <?php if (isset($presentations[0]['titreImage']) ) : ?>
                    <figcaption class="titreImage">
                        <p><?= $presentations[0]['titreImage']?></p>
                    </figcaption>
                    <?php endif ?>
                </figure>
                <?php if (isset($presentations[0]['adresse']) ) : ?>
                    <div class="champs">
                        <div class="icone_titre">
                            <i class="fas fa-map-marker-alt"></i>
                            <h2>Adresse</h2>
                        </div>
                        <p><?= $presentations[0]['adresse']?></p>
                    </div>
                <?php endif ?>
                <?php if (isset($presentations[0]['tel']) ) : ?>
                    <div class="champs">
                        <div class="icone_titre">
                            <i class="fas fa-phone-square-alt"></i>
                            <h2>Téléphone</h2>
                        </div>
                        <p><?= $presentations[0]['tel']?></p>
                    </div>
                <?php endif ?>
                <?php if (isset($presentations[0]['mail']) ) : ?>
                    <div class="champs">
                        <div class="icone_titre">
                            <i class="fas fa-envelope"></i>
                            <h2>E-mail</h2>
                        </div>
                        <p><?= $presentations[0]['mail']?></p>
                    </div>
                <?php endif ?>
        </aside>
    </div>
</div>
</main>
